version: '3.7'

services:
  postgres:
    container_name: postgres
    image: postgres:15
    env_file:
      - .development.env
    environment:
      POSTGRES_USER: duke
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: nestdb
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  app:
    container_name: app
    build:
      context: .
    env_file:
      - .development.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 5000:5000
      - 9229:9229
    command: npm run start:dev
    depends_on:
      - postgres
    restart: always

volumes:
  postgres-data:
